### ISSUE TITLE
Config local and prod domains

### ISSUE THREAD

**Issue by borisdamevin** [gilbitron/Raneto#23]
Hello,

I do not understand how to configure a domain normal places of ``localhost: 3000`` that either locally or on my server. Heroku is still not mandatory?

How to do this please?

Thank you.

**Comment by ryanlelek** [comment]
@borisdamevin, what platform are you currently on? (Windows, Mac OS X, Linux, other)
As @akmalhisyam mentioned, you could change the IP address locally, but you shouldn't need to do this for local testing.

- __Windows__: Type "node bin/www" from the command prompt [Node on Windows](http://www.altifysoftware.com/developing-node-js-in-windows/)
- __Mac OS X and Linux__: Type "./bin/www" from the Raneto directory

**Comment by ryanlelek** [comment]
@borisdamevin, after re-reading your question, it seems like you're trying to deploy to a service other than Heroku. If you're using a cloud provider, they should be able to help you out.

Managing domains is out of the scope of Raneto and Node.js as well, especially for security reasons.
When deploying to a public server and not using Heroku or a similar service, it is recommended to put Nginx, Apache, or another proven web server in front of Node.js instead of exposing Node.js directly.

Consider using Nginx to handle domains and send requests to Node.js, using the following configuration and running your Node.js scripts with a [process manager](http://expressjs.com/advanced/pm.html).

```
server {
    listen 80;
    server_name docs.example.com;
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```

Closing this issue for now.
