### ISSUE TITLE
How to run Raneto on Apache2 Server?

### ISSUE THREAD

**Issue by DoctorRiceYouSee** [gilbitron/Raneto#335]
I'm completely new to running websites on servers and I was wondering how I can run Raneto on an Apache2 server. Do I need to change anything in the Raneto files? Some guidance would be very appreciated. Thanks!

**Comment by simdo01** [comment]
I'd like to know this as well. I am running Raneto under a virtual host on Apache (on Cent OS 8) and the scripts, css etc... do not load. It doesn't appear to be auth problem...just a path problem. Please advise. Thx

**Comment by ryanlelek** [comment]
Hello, I'm personally not familiar with Apache as much as Nginx.
This type of issue starts to get about 50/50 outside the scope of Raneto, and is more "DevOps"-y.

There are a few options and examples at the bottom of the main page, including Nginx and Docker.
If you're not tied to Apache2 for other reasons/projects, I'd suggest looking at these for examples and ideas:
https://github.com/gilbitron/Raneto#related-projects

No matter what you choose and use, you shouldn't need to change any Raneto files except for settings.
One example is the `base_url` option, to point to your full domain/subdomain (like `https://raneto.example.com`)

One other thing... Apache, Nginx, etc are essentially "static file servers"
Raneto has a basic one of these built-in, but because Apache/Nginx are usually "in front of" Raneto, they'll serve static files first and they wont get to Raneto.

Some quick searching led to this tutorial that goes into more detail, which seems to cover the basic steps.
https://tecadmin.net/apache-frontend-proxy-nodejs/

Let us know how that goes

**Comment by endo64** [comment]
@DoctorRiceYouSee @simdo01 You need to setup a normal web site on your Apache server and configure it as a reverse proxy. This way Apache will accept the connection on HTTP port 80 or 443 (for HTTPS) and redirect the requests to the NodeJS on port 3000 (or whatever port you configured)

An example configuration for Apache is:

```
<VirtualHost *:80>
    ProxyPreserveHost On

    ProxyPass / http://127.0.0.1:3000/
    ProxyPassReverse / http://127.0.0.1:3000/
</VirtualHost>
```

Search for "Apache reverse proxy": [Ref1](https://www.digitalocean.com/community/tutorials/how-to-use-apache-as-a-reverse-proxy-with-mod_proxy-on-ubuntu-16-04) [Ref2](https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html)

**Comment by ryanlelek** [comment]
Thank you for adding your thoughts @endo64 
@DoctorRiceYouSee @simdo01 

Endo's response is generally correct.
Here's another article that explains the process
https://tecadmin.net/apache-frontend-proxy-nodejs/

Closing for now, as it's out of the scope of Raneto.
We'll help where we can, so re-open this if you need additional help (and include config files)

We may also create an easy deployment option/docs in addition to the Heroku option already added
