### ISSUE TITLE
Add path to search result

### ISSUE THREAD

**Issue by saelfaer** [gilbitron/Raneto#38]
when searching, you now get the title of the page and part of the page content as result, however if you use folders to categorize it could be useful to get the path to the file visualized with the search result.

this could be configurable with a flag.

usecase:  create a folder for backend and 1 for frontend code. both need documentation about how multilanguage or logging or any other generic idea is being handled.
but you end up with 2 files called `logging.md`  or worse, you have to add the category in the title again which is tedious ...

**Comment by ryanlelek** [comment]
@saelfaer if you're still interested, this has been fixed.

Download the latest master branch, install, and then:
- search for "contrib" which should return 1 result without path info since it's a main article
- search for "config" which should return many results, all of which with a path shown in gray

If you prefer a different style, please edit in your local copy and submit a PR if you'd like to share changes
