### ISSUE TITLE
Access config variables from markdown files?

### ISSUE THREAD

**Issue by billsinc** [gilbitron/Raneto#42]
Is it possible to access the config variables from the markdown files themselves?  I added a line to the renato.js file to replace a content variable but wanted to know if there is an easier way?  Thanks.

**Comment by vyp** [comment]
I think it should be possible, but not sure if it would possible with the current code. Probably require some patches. For example, if you look at https://github.com/gilbitron/Raneto-Core/blob/master/raneto.js, you can see there's a `processVars` method to insert some config variables, so you would need to change this to loop through all the config variables, if I understood correctly?

---

Just ftr, I'm not a huge fan of this though, because parsing the document should be left to the parser imo. There's too many things that could go wrong or conflict, and it effectively changes your document's markdown syntax, even if in a very minor way.

If it's a must though, it should be post-processing on the converted html, not pre-processing on the raw markdown text: https://github.com/gilbitron/Raneto/blob/master/app.js#L81-82. That way you could use something to at least navigate the structure of the document (some html dom parser/navigator) and ignore selected elements if wanted, instead of just doing a simple but inflexible global string replacement as is done in `processVars`.

**Comment by billsinc** [comment]
I think it's an elegant project so I don't want to over-complicate things.  The documentation problems I'm trying to solve for include white-label branding, which I think I can handle using the mustache templates, the ability to re-use documentation fragments (I don't want to update something in multiple places when it changes) and finally the ability to use variables for certain API parameters in our documentation that are client specific.  

For instance I added,
`if (typeof raneto.config.company_name !== 'undefined') markdownContent = markdownContent.replace(/\%company_name\%/g, raneto.config.company_name);` 
so that I can assign a different company name depending on who's white-labeling it (determined at this point by hostname).

I'm trying to stick with markdown rather than HTML, JS or PHP for the actual docs themselves so that they can be maintained by non-technical users.  I've evaluated other open source wiki solutions but none of them meets our needs above.  I very much appreciate your response.

**Comment by vyp** [comment]
> The documentation problems I'm trying to solve for include white-label branding, which I think I can handle using the mustache templates, the ability to re-use documentation fragments (I don't want to update something in multiple places when it changes)

Should that can be a "can't"? Either way, yes I think it's best if site-wide variables are handled by templates (as that's a main reason they exist), but I can understand situations where this might not be possible ala your case.

So what you did, if that works for you and you're okay with using `%company_name%` in your documents, that's great and I'm not going to tell you to stop. That's also exactly what I imagined when I said might 'require some patches'. (Ideally, it would loop through all or most of the config variables so everyone does not have to hard code it into `raneto.js` for whatever variable name they want. Or perhaps have a file named `global-variables.json` somewhere which raneto could check for.)

So to answer your question, I don't currently think there's a better way to do it unfortunately. But I should stress that I'm not affiliated with the project or anything (not the author or a 'core dev'). I'm simply judging it by reading over the source code which is easy since it is a simple project.

I think my favourite solution to this would be how [pandoc](http://johnmacfarlane.net/pandoc/README.html) does variables and templates but I think it is probably too complicated for this project. As you say, raneto's simplicity is a plus point. But in case pandoc's methods work for you, you could check out [gitit](https://github.com/jgm/gitit) and/or [gitit2](https://github.com/jgm/gitit2) as they are 'wiki' programs that use pandoc. Although it might be overkill, it's robust and featureful so there's a good chance it might do what you want.

Downside ofc is that it's written in Haskell, requiring a hefty download size for the haskell compiler and libraries, so probably not as simple as you already have with raneto (which is also what attracted me to raneto).

> I'm trying to stick with markdown rather than HTML, JS or PHP for the actual docs themselves so that they can be maintained by non-technical users.

Of course, that's the whole point of markdown right. I was just mentioning what *raneto* should do to handle substituting in config variables, not *you* specifically. Unfortunately, the author of this project seems to be working on other things at the moment and hasn't had any activity in raneto for about 5 months. But if you have more questions, I'm still happy to try and answer them if I can, though not sure how useful I can be without the author's input.
