### ISSUE TITLE
nodejs not node on Ubuntu Server

### ISSUE THREAD

**Issue by nicekiwi** [gilbitron/Raneto#44]
On an ubuntu server nodejs is accessed via the "nodejs" command, not the "node" command.

So the "npm start" command will break.

**Comment by vyp** [comment]
So how do you suggest to fix it? If you have a solution that is. 

What about simply aliasing `node` as `nodejs` in your shell? (And then consequently mentioning that somewhere for ubuntu server users.)

**Comment by nicekiwi** [comment]
I suppose there not much more you could do, without making things overly complicated that is.

**Comment by vyp** [comment]
Well I guess a small script may be written (but how I do not exactly know), but I think a simpler solution would be for the user themselves handle this via aliases, or if using a script or something, use the actual command itself (instead of `npm start`), but substitute `nodejs` in place of `node`.

Keep in mind I'm not the owner, nor a collaborator of this project, so I'm not speaking for them.

**Comment by inexion** [comment]
sudo ln -s /usr/bin/nodejs /usr/bin/node

**Comment by vyp** [comment]
@inexion Obvious solution, not sure why I didn't think of that lol. Thanks!

**Comment by ryanlelek** [comment]
As @inexion mentioned, a symlink of /usr/bin/nodejs to /usr/bin/node is a clean solution.  
Alternatively, you can alter ./bin/www in the Raneto project to use "nodejs" instead of "node"

Closing issue.
