### ISSUE TITLE
Basic Auth Guide / Password Feature

### ISSUE THREAD

**Issue by kevinmann** [gilbitron/Raneto#49]
Is there a way of getting Basic Auth working with Raneto?  I am really struggling, but I am new to node.js.

**Comment by eighteyes** [comment]
https://github.com/gilbitron/Raneto/pull/50

**Comment by ryanlelek** [comment]
@kevinmann, A solution for password protection via [HTTP Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) was written by @eighteyes and has since been merged into the main project.

You can add a password by editing the ./config.js file in the updated codebase.

Let me know if you have questions.
Closing Issue.
