### ISSUE TITLE
Feature Request for Missing but Necessary Features.

### ISSUE THREAD

**Issue by geraldtay** [gilbitron/Raneto#54]
Some of the critical functions that I feel Raneto might need is as follows:
* Login page and user management.
* Upload and management of documents or some form of document editing from the website.
* Document history and archiving.
* HTTPS support activation from webpage.

**Comment by ryanlelek** [comment]
Hello @geraldtay,

Those features are useful, although most are beyond the scope of Raneto.From my view, Raneto is meant for a few team members to create documentation instead of as a collaboration platform. Once you go beyond ~5 people accessing and editing Raneto, the limits really show themselves as you pointed out.

You might be more interested in a wiki, one of the most popular being Wikimedia. There are plenty of Wiki service providers and projects out there to give you more control over user management, activation, and history.

If you do end up building these features for Raneto, please send us a pull request and we'll add them for other users and give you credit.
