### ISSUE TITLE
How to show '{{last_modified}}'  variable on home.html

### ISSUE THREAD

**Issue by liuweicode** [gilbitron/Raneto#56]
I want to append last modified time to the '{{title}}' variable, how should I do?

**Comment by ryanlelek** [comment]
Hi @liuweicode,

I've submitted a partial fix for this on the master branch.
Here's how it works, and why it's not a total fix...

First, I'm going to guess you want the "last_modified" variable to reflect the last time the Home page has changed, and since Home shows each and every page in content/, we would have to scan every Markdown file to get the most recent.

Instead, as a temporary fix, the "last_modified" variable will reflect when ./views/home.html was last edited. Whenever you update documents, open and save ./views/home.html without any changes, or just execute `touch ./views/home.html` on Linux and OS X and that should get you going until a better fix can be made.
