### ISSUE TITLE
Транслит в URL

### ISSUE THREAD

**Issue by mtaobiz** [gilbitron/Raneto#61]
Если название файлов и папок делать на русском, то в урл будет кириллица. Файлы ладно - можно и в латинице делать, так как в файле есть title, но как сделать папки на английском, но чтобы в URL было на латинице?

**Comment by ryanlelek** [comment]
Hi @mtaobiz,
I tried running the question through Google Translate.
Unfortunately, I did not understand the question.
Please resubmit your question in English.

(via Google Translate -> Russian)
Я попытался запустить вопрос через Google Translate.
К сожалению, я не понял вопроса.
Пожалуйста, повторите свой вопрос на английском языке.

**Comment by mtaobiz** [comment]
How do I get the name of the folder were in English, and the site was in Russian. As to the content title, you can add folders to the 'Title' parameter.
For example: my folder name 'Юбка' and URL will be http://site.com/Юбка/name-content
i want to make 'Title' for folder

**Comment by yaruson** [comment]
Hello @ryanlelek 

@mtaobiz 's question is related to usage of non-Latin characters in category names or article names. Particularly, one can't use Cyrillic names, because they are translated to something like `%D0%9F%D1%80%D0%BE` while saving article.

There are three points:
* Folder and file names are used as-is, i.e. category name 'Проверка' corresponds to 'Проверка' folder
* User can create Cyrillic category and corresponding folder will be created with no problem, as it's name is taken from form field
* When user clicks 'Save page', category and article names are taken from page URL; and at this point we actually get URL-encoded (bad for us) names, that doesn't have literally corresponding folders and files within server-side file system

I'd like to suggest using [decodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI) function at client-side `raneto.js` code to unescape category and folder names. Of course, we have to evaluate impact on security, but basically idea is like this:

```javascript
    // Save Page
    $(".save-page").click(function () {
      var file_arr = window.location.pathname.split("/");
      file_arr.pop();
      $("#entry-markdown").next(".CodeMirror")[0].CodeMirror.save();
      $.post("/rn-edit", {
        file    : decodeURI(file_arr.join("/")),
        content : $("#entry-markdown").val()
      } // ...
```

**Comment by ryanlelek** [comment]
Thank you for the explanation @yaruson and the pull request.

To make sure I understand the problem:
1. non-latin characters like "Проверка" in the URI correspond to the file on the file system
2. the browser URL-encodes these values
3. the file system cannot find the file because the filename is not URI decoded
4. we can solve this by decoding the URI before sending to the backend

Is this correct?

**Comment by yaruson** [comment]
@ryanlelek sure, that's what I'd like to say.

**Comment by ryanlelek** [comment]
@mtaobiz Please try the new version.

@yaruson made a patch that should solve your issue.
