### ISSUE TITLE
password protected admin login for "online editing page"

### ISSUE THREAD

**Issue by eijoac** [gilbitron/Raneto#77]
How about add a password protected admin login for the online editing function? In this way, users can access the knowledge base without password but only admin with a password can edit the pages. The current "allow_editing: true" + basic auth in the config.default.js won't do the trick.

**Comment by markphd** [comment]
This is really a nice feature, maybe separate the login route from the content so people who are successfully logged in are the only ones who can have the edit function.

@ryanlelek I'm trying to "hack" into the code, in `app/index.js` can I add a function like:

    function isAuthenticated(req, res, next) {
      if (req.session.loggedIn == false) {
        res.send("You must be logged in");
        res.redirect('/login');
      } 
      return next();
    }

..and so pass it in `app.post('/rn-edit', isAuthenticated, function (req, res, next)` ?

At the moment if I'm not logged and I set `allow_editing : true`, in Edit mode POST requests result in 500 Internal Server Error which to me is a good sign that something is going on. I just don't know what's next or if I'm on the right track. 

I'm learning Node.js so please be gentle. :) I appreciate any help. :+1:

**Comment by ryanlelek** [comment]
@markphd You are in the right mindset, defining middleware and then adding it to the middleware stack.
My guess just from looking at the code you provided is `req.session` may not be defined and thus, the property `req.session.loggedIn` does not exist which is why you get the 500 error. Simply a guess though! Feel free to ask me about any other Node.js questions too, directly
