### ISSUE TITLE
[RFC] Merge Raneto and Raneto-Core

### ISSUE THREAD

**Issue by Radiergummi** [gilbitron/Raneto#99]
I'd like to hear your opinions on this, hence the RFC-Tag.  
Would it make sense to merge Raneto and the Raneto-Core package into one, providing not an example server implementation but one that is working out of the box? I had to make changes to the core package a few days ago and realized it is pretty impractical to npm-update that way. Besides, that would make for a much cleaner directory layout.

**Comment by ryanlelek** [comment]
You are right, thanks for bringing this up.
I had this on a list to discuss with Gilbert and doing it here is an even better idea.

I see this going 2 ways so far:
1) We merge Raneto Core into Raneto and make a separate example repository for viewers
2) Underlying functionality of Raneto gets moved to Raneto Core, adding tests along the way and the Raneto repo become the example repository.

Open to others as well

**Comment by Radiergummi** [comment]
I'd propose merging Raneto Core into Raneto and creating a new Raneto-Server (or whatever) repository containing a properly named and ready-to-use app with Raneto listed in the package.json as a dependency. The repo could also contain a developer branch with the debug module enabled etc.  
What do you think?

**Comment by ryanlelek** [comment]
Yep, we can extract the `example/` directory as a starting point for the ready-to-use demo including Raneto's own documentation contents.

So long as the example repo contains "example", "demo" or something similar, and a link back to the main repository, that should all work fine

**Comment by draptik** [comment]
Maybe a [Yeoman](http://yeoman.io/) generator would help?

**Comment by Radiergummi** [comment]
Yeoman sounds like a perfect match, though I'd rather see it as an alternative beneath the demo repo, considering installing Yeoman is an additional step that seems maybe too complicated for some people.

**Comment by ryanlelek** [comment]
Having both a repo and Yeoman as options would work.  
I'm in the camp of wanting a regular repo and wouldn't mess with Yeoman.

**Comment by gilbitron** [comment]
The reason I originally split out Raneto and Raneto Core was because I imagined that down the line Raneto Core could be the basis for all sorts of "flat file" apps, not just a knowledgebase (e.g. Blog, CMS etc.). It also meant the core could be isolated and have better tests, then you could include it as a dependency into this repo, similar to the structure of Laravel. I'm aware this makes development slightly harder but I still think it's a good solution.

> I'd propose merging Raneto Core into Raneto and creating a new Raneto-Server (or whatever) repository containing a properly named and ready-to-use app

I don't see how this is any different to what we have just now>

> Underlying functionality of Raneto gets moved to Raneto Core, adding tests along the way, and the Raneto repo become the example repository.

I'm not necessarily adverse to this. My feelings are that this repo should always be the "ready-to-use app" and include any "knowledgebase" specific code. Any functionality that has a more general application (e.g. folder structure, categories, file parsing etc.) should go into Core.

One other way we could structure it is to split out the "knowledgebase" specific code into it's own repo and make this repo have two dependencies: `raneto-core` and `raneto-knowledgebase`. That way core can remain generic and `raneto-knowledgebase` can build/extend the functionality as needed.

**Comment by yaruson** [comment]
I've got a newbie question :smiley: I have two repositories within a folder: `raneto` and `raneto-core`. How to make *raneto* use *raneto-core* from neighbour repository and not its own `node_modules`?

**Comment by gilbitron** [comment]
@yaruson The easiest thing to do is make the `ranteo` package.json use a [local path](https://docs.npmjs.com/files/package.json#local-paths) to `raneto-core`.

**Comment by Sparticuz** [comment]
Any update on this? I'd like to help with some bugs but wanted to wait to see if there was any movement on this?

**Comment by ryanlelek** [comment]
Marked the Raneto-Core repo as deprecated a month or two ago, and made it clear no new Issues/PRs would be accepted while I reached out to resolve remaining issues.

I'd say it's fine to move on now, without responses, due to the length of time.
The opportunity was there, but we have to keep moving.

So, I'll merge Raneto-Core into Raneto tonight and create a maintenance release so we can move forward on locking down a v1.0

**Comment by ryanlelek** [comment]
Raneto-Core has now been merged and will be part of the next release
This should happen within a few days as PRs close out.

Still not sure how I feel on a separate example repository, so let's keep it all in one for now

**Comment by ryanlelek** [comment]
Completed.
Closing
